name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  push:
    branches:
      - '**' # Every branch
  pull_request:
    branches:
      - main
      - develop

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run security scan
        run: |
          npm audit --audit-level=moderate > npm_audit_output.txt
          cat npm_audit_output.txt

      - name: Upload security scan report
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-report
          path: npm_audit_output.txt

  notifications:
    needs: security-scan
    runs-on: ubuntu-latest

    steps:
      - name: Notify Always
        if: always()
        run: echo "This will always run"

      - name: Notify Success
        if: success()
        run: echo "This runs on success"

      - name: Notify Failure
        if: failure()
        run: echo "This runs on failure"

      - name: Notify Cancelled
        if: cancelled()
        run: echo "This runs on cancelled"
